/*
 * Decompiled with CFR 0_102.
 */
package org.gjt.sp.jedit.syntax;

import org.gjt.sp.jedit.syntax.CTokenMarker;
import org.gjt.sp.jedit.syntax.KeywordMap;

public class PovrayTokenMarker
extends CTokenMarker {
    private static KeywordMap povrayKeywords;

    public PovrayTokenMarker() {
        super(true, true, PovrayTokenMarker.getKeywords());
    }

    public static KeywordMap getKeywords() {
        if (povrayKeywords == null) {
            povrayKeywords = new KeywordMap(false);
            povrayKeywords.add("adaptive", 6);
            povrayKeywords.add("agate", 6);
            povrayKeywords.add("agate_turb", 6);
            povrayKeywords.add("all", 6);
            povrayKeywords.add("alpha", 6);
            povrayKeywords.add("ambient", 6);
            povrayKeywords.add("angle", 6);
            povrayKeywords.add("arc_angle", 6);
            povrayKeywords.add("area_light", 8);
            povrayKeywords.add("atmosphere", 8);
            povrayKeywords.add("atmospheric_attenuation", 6);
            povrayKeywords.add("background", 8);
            povrayKeywords.add("bicubic_patch", 8);
            povrayKeywords.add("blob", 8);
            povrayKeywords.add("blue", 4);
            povrayKeywords.add("bounded_by", 6);
            povrayKeywords.add("box", 8);
            povrayKeywords.add("bozo", 6);
            povrayKeywords.add("brilliance", 6);
            povrayKeywords.add("bumps", 6);
            povrayKeywords.add("bump_map", 8);
            povrayKeywords.add("bump_size", 6);
            povrayKeywords.add("camera", 8);
            povrayKeywords.add("checker", 6);
            povrayKeywords.add("clipped_by", 6);
            povrayKeywords.add("clock", 4);
            povrayKeywords.add("color", 6);
            povrayKeywords.add("color_map", 8);
            povrayKeywords.add("colour", 6);
            povrayKeywords.add("colour_map", 8);
            povrayKeywords.add("component", 6);
            povrayKeywords.add("composite", 6);
            povrayKeywords.add("cone", 8);
            povrayKeywords.add("crand", 6);
            povrayKeywords.add("cubic", 8);
            povrayKeywords.add("cylinder", 8);
            povrayKeywords.add("cylindrical_mapping", 6);
            povrayKeywords.add("declare", 4);
            povrayKeywords.add("default", 4);
            povrayKeywords.add("dents", 6);
            povrayKeywords.add("difference", 6);
            povrayKeywords.add("diffuse", 6);
            povrayKeywords.add("direction", 6);
            povrayKeywords.add("disc", 8);
            povrayKeywords.add("distance", 6);
            povrayKeywords.add("dump", 6);
            povrayKeywords.add("emitting", 6);
            povrayKeywords.add("falloff", 6);
            povrayKeywords.add("falloff_angle", 6);
            povrayKeywords.add("filter", 6);
            povrayKeywords.add("finish", 8);
            povrayKeywords.add("flatness", 6);
            povrayKeywords.add("fog", 8);
            povrayKeywords.add("fog_alt", 6);
            povrayKeywords.add("fog_offset", 6);
            povrayKeywords.add("fog_type", 6);
            povrayKeywords.add("frequency", 6);
            povrayKeywords.add("gif", 4);
            povrayKeywords.add("gradient", 8);
            povrayKeywords.add("granite", 6);
            povrayKeywords.add("green", 4);
            povrayKeywords.add("height_field", 8);
            povrayKeywords.add("hexagon", 6);
            povrayKeywords.add("iff", 4);
            povrayKeywords.add("image_map", 8);
            povrayKeywords.add("include", 4);
            povrayKeywords.add("interpolate", 6);
            povrayKeywords.add("intersection", 6);
            povrayKeywords.add("inverse", 6);
            povrayKeywords.add("ior", 6);
            povrayKeywords.add("halo", 8);
            povrayKeywords.add("jitter", 6);
            povrayKeywords.add("lambda", 6);
            povrayKeywords.add("leopard", 6);
            povrayKeywords.add("light_source", 8);
            povrayKeywords.add("linear", 6);
            povrayKeywords.add("linear_spline", 6);
            povrayKeywords.add("location", 6);
            povrayKeywords.add("looks_like", 6);
            povrayKeywords.add("look_at", 6);
            povrayKeywords.add("mandel", 6);
            povrayKeywords.add("map_type", 6);
            povrayKeywords.add("marble", 6);
            povrayKeywords.add("material_map", 8);
            povrayKeywords.add("max_intersections", 5);
            povrayKeywords.add("max_trace_level", 5);
            povrayKeywords.add("merge", 6);
            povrayKeywords.add("metallic", 6);
            povrayKeywords.add("normal", 8);
            povrayKeywords.add("no_shadow", 6);
            povrayKeywords.add("object", 8);
            povrayKeywords.add("off", 4);
            povrayKeywords.add("on", 4);
            povrayKeywords.add("octaves", 6);
            povrayKeywords.add("omega", 6);
            povrayKeywords.add("once", 6);
            povrayKeywords.add("onion", 6);
            povrayKeywords.add("open", 6);
            povrayKeywords.add("phase", 6);
            povrayKeywords.add("phong", 6);
            povrayKeywords.add("phong_size", 6);
            povrayKeywords.add("pigment", 8);
            povrayKeywords.add("plane", 8);
            povrayKeywords.add("point_at", 6);
            povrayKeywords.add("poly", 8);
            povrayKeywords.add("pot", 4);
            povrayKeywords.add("prism", 8);
            povrayKeywords.add("quadric", 8);
            povrayKeywords.add("quartic", 8);
            povrayKeywords.add("quick_color", 6);
            povrayKeywords.add("quick_colour", 6);
            povrayKeywords.add("radial", 6);
            povrayKeywords.add("radius", 6);
            povrayKeywords.add("rainbow", 8);
            povrayKeywords.add("raw", 6);
            povrayKeywords.add("red", 4);
            povrayKeywords.add("reflection", 6);
            povrayKeywords.add("refraction", 6);
            povrayKeywords.add("rgb", 6);
            povrayKeywords.add("rgbf", 6);
            povrayKeywords.add("rgbt", 6);
            povrayKeywords.add("right", 6);
            povrayKeywords.add("ripples", 6);
            povrayKeywords.add("rotate", 6);
            povrayKeywords.add("roughness", 6);
            povrayKeywords.add("samples", 6);
            povrayKeywords.add("scale", 6);
            povrayKeywords.add("scattering", 6);
            povrayKeywords.add("shadowless", 6);
            povrayKeywords.add("sky", 8);
            povrayKeywords.add("sky_sphere", 8);
            povrayKeywords.add("smooth", 8);
            povrayKeywords.add("smooth_triangle", 8);
            povrayKeywords.add("sor", 8);
            povrayKeywords.add("specular", 6);
            povrayKeywords.add("sphere", 8);
            povrayKeywords.add("spherical_mapping", 6);
            povrayKeywords.add("spiral1", 6);
            povrayKeywords.add("spotlight", 6);
            povrayKeywords.add("spotted", 6);
            povrayKeywords.add("sturm", 6);
            povrayKeywords.add("text", 8);
            povrayKeywords.add("texture", 8);
            povrayKeywords.add("tga", 4);
            povrayKeywords.add("threshold", 6);
            povrayKeywords.add("tightness", 6);
            povrayKeywords.add("tile0", 6);
            povrayKeywords.add("tiles", 6);
            povrayKeywords.add("torus", 8);
            povrayKeywords.add("translate", 6);
            povrayKeywords.add("transmit", 6);
            povrayKeywords.add("triangle", 8);
            povrayKeywords.add("ttf", 4);
            povrayKeywords.add("turb_depth", 6);
            povrayKeywords.add("turbulence", 6);
            povrayKeywords.add("type", 6);
            povrayKeywords.add("union", 6);
            povrayKeywords.add("up", 6);
            povrayKeywords.add("use_color", 6);
            povrayKeywords.add("use_colour", 6);
            povrayKeywords.add("use_index", 6);
            povrayKeywords.add("u_steps", 6);
            povrayKeywords.add("version", 5);
            povrayKeywords.add("v_steps", 6);
            povrayKeywords.add("water_level", 6);
            povrayKeywords.add("waves", 6);
            povrayKeywords.add("width", 6);
            povrayKeywords.add("wood", 6);
            povrayKeywords.add("wrinkles", 6);
            povrayKeywords.add("x", 4);
            povrayKeywords.add("y", 4);
            povrayKeywords.add("z", 4);
        }
        return povrayKeywords;
    }
}

