/*
 * Decompiled with CFR 0_102.
 */
package org.gjt.sp.jedit.syntax;

import javax.swing.text.Segment;
import org.gjt.sp.jedit.syntax.KeywordMap;
import org.gjt.sp.jedit.syntax.TokenMarker;

public class TSQLTokenMarker
extends TokenMarker {
    boolean bracket = false;
    protected static KeywordMap sqlKeywords;
    private boolean cpp;
    private boolean javadoc;
    protected KeywordMap keywords;
    private int lastOffset;
    private int lastKeyword;

    public TSQLTokenMarker() {
        this(TSQLTokenMarker.getKeywords());
    }

    public TSQLTokenMarker(KeywordMap keywordMap) {
        this.keywords = keywordMap;
    }

    public byte markTokensImpl(byte by, Segment segment, int n) {
        int n2;
        char[] arrc = segment.array;
        this.lastOffset = n2 = segment.offset;
        this.lastKeyword = n2;
        int n3 = segment.count + n2;
        block21 : for (int i = n2; i < n3; ++i) {
            int n4 = i + 1;
            char c = arrc[i];
            switch (by) {
                case 0: {
                    switch (c) {
                        case '[': {
                            this.bracket = true;
                        }
                        case '\"': {
                            this.doKeyword(segment, i, c);
                            this.addToken(i - this.lastOffset, by);
                            by = (byte)3;
                            this.lastOffset = this.lastKeyword = i;
                            continue block21;
                        }
                        case '\'': {
                            this.doKeyword(segment, i, c);
                            this.addToken(i - this.lastOffset, by);
                            by = (byte)4;
                            this.lastOffset = this.lastKeyword = i;
                            continue block21;
                        }
                        case ':': {
                            if (this.lastKeyword == n2) {
                                if (this.doKeyword(segment, i, c)) continue block21;
                                this.addToken(n4 - this.lastOffset, 5);
                                this.lastOffset = this.lastKeyword = n4;
                                continue block21;
                            }
                            if (!this.doKeyword(segment, i, c)) continue block21;
                            continue block21;
                        }
                        case '/': {
                            this.doKeyword(segment, i, c);
                            if (n3 - i <= 1 || arrc[n4] != '*') continue block21;
                            this.addToken(i - this.lastOffset, by);
                            this.lastOffset = this.lastKeyword = i;
                            by = (byte)2;
                            continue block21;
                        }
                        case '-': {
                            this.doKeyword(segment, i, c);
                            if (n3 - i <= 1) continue block21;
                            switch (arrc[n4]) {
                                case '-': {
                                    this.addToken(i - this.lastOffset, by);
                                    this.addToken(n3 - i, 1);
                                    this.lastOffset = this.lastKeyword = n3;
                                    break block21;
                                }
                            }
                            continue block21;
                        }
                    }
                    if (Character.isLetterOrDigit(c) || c == '_') continue block21;
                    this.doKeyword(segment, i, c);
                    continue block21;
                }
                case 2: {
                    if (c != '*' || n3 - i <= 1 || arrc[n4] != '/') continue block21;
                    this.addToken(++i + 1 - this.lastOffset, by);
                    by = 0;
                    this.lastOffset = this.lastKeyword = i + 1;
                    continue block21;
                }
                case 3: {
                    if (c != '\"' && c != ']') continue block21;
                    this.addToken(n4 - this.lastOffset, by);
                    by = 0;
                    this.lastOffset = this.lastKeyword = n4;
                    this.bracket = false;
                    continue block21;
                }
                case 4: {
                    if (c != '\'') continue block21;
                    this.addToken(n4 - this.lastOffset, by);
                    by = 0;
                    this.lastOffset = this.lastKeyword = n4;
                    continue block21;
                }
                default: {
                    throw new InternalError("Invalid state: " + by);
                }
            }
        }
        if (by == 0) {
            this.doKeyword(segment, n3, '\u0000');
        }
        switch (by) {
            case 3: 
            case 4: {
                this.addToken(n3 - this.lastOffset, this.bracket ? 3 : 10);
                by = (byte)(this.bracket ? 3 : 0);
                break;
            }
            case 7: {
                this.addToken(n3 - this.lastOffset, by);
                by = 0;
                break;
            }
            default: {
                this.addToken(n3 - this.lastOffset, by);
            }
        }
        return by;
    }

    public static KeywordMap getKeywords() {
        if (sqlKeywords == null) {
            sqlKeywords = new KeywordMap(true);
            sqlKeywords.add("ADD", 6);
            sqlKeywords.add("ALTER", 6);
            sqlKeywords.add("ANSI_NULLS", 6);
            sqlKeywords.add("AS", 6);
            sqlKeywords.add("ASC", 6);
            sqlKeywords.add("AUTHORIZATION", 6);
            sqlKeywords.add("BACKUP", 6);
            sqlKeywords.add("BEGIN", 6);
            sqlKeywords.add("BREAK", 6);
            sqlKeywords.add("BROWSE", 6);
            sqlKeywords.add("BULK", 6);
            sqlKeywords.add("BY", 6);
            sqlKeywords.add("CASCADE", 6);
            sqlKeywords.add("CHECK", 6);
            sqlKeywords.add("CHECKPOINT", 6);
            sqlKeywords.add("CLOSE", 6);
            sqlKeywords.add("CLUSTERED", 6);
            sqlKeywords.add("COLUMN", 6);
            sqlKeywords.add("COMMIT", 6);
            sqlKeywords.add("COMMITTED", 6);
            sqlKeywords.add("COMPUTE", 6);
            sqlKeywords.add("CONFIRM", 6);
            sqlKeywords.add("CONSTRAINT", 6);
            sqlKeywords.add("CONTAINS", 6);
            sqlKeywords.add("CONTAINSTABLE", 6);
            sqlKeywords.add("CONTINUE", 6);
            sqlKeywords.add("CONTROLROW", 6);
            sqlKeywords.add("CREATE", 6);
            sqlKeywords.add("CURRENT", 6);
            sqlKeywords.add("CURRENT_DATE", 6);
            sqlKeywords.add("CURRENT_TIME", 6);
            sqlKeywords.add("CURSOR", 6);
            sqlKeywords.add("DATABASE", 6);
            sqlKeywords.add("DBCC", 6);
            sqlKeywords.add("DEALLOCATE", 6);
            sqlKeywords.add("DECLARE", 6);
            sqlKeywords.add("DEFAULT", 6);
            sqlKeywords.add("DELETE", 6);
            sqlKeywords.add("DENY", 6);
            sqlKeywords.add("DESC", 6);
            sqlKeywords.add("DISK", 6);
            sqlKeywords.add("DISTINCT", 6);
            sqlKeywords.add("DISTRIBUTED", 6);
            sqlKeywords.add("DOUBLE", 6);
            sqlKeywords.add("DROP", 6);
            sqlKeywords.add("DUMMY", 6);
            sqlKeywords.add("DUMP", 6);
            sqlKeywords.add("ELSE", 6);
            sqlKeywords.add("END", 6);
            sqlKeywords.add("ERRLVL", 6);
            sqlKeywords.add("ERROREXIT", 6);
            sqlKeywords.add("ESCAPE", 6);
            sqlKeywords.add("EXCEPT", 6);
            sqlKeywords.add("EXEC", 6);
            sqlKeywords.add("EXECUTE", 6);
            sqlKeywords.add("EXIT", 6);
            sqlKeywords.add("FETCH", 6);
            sqlKeywords.add("FILE", 6);
            sqlKeywords.add("FILLFACTOR", 6);
            sqlKeywords.add("FLOPPY", 6);
            sqlKeywords.add("FOR", 6);
            sqlKeywords.add("FOREIGN", 6);
            sqlKeywords.add("FREETEXT", 6);
            sqlKeywords.add("FREETEXTTABLE", 6);
            sqlKeywords.add("FROM", 6);
            sqlKeywords.add("FULL", 6);
            sqlKeywords.add("GOTO", 6);
            sqlKeywords.add("GRANT", 6);
            sqlKeywords.add("GROUP", 6);
            sqlKeywords.add("HAVING", 6);
            sqlKeywords.add("HOLDLOCK", 6);
            sqlKeywords.add("IDENTITY_INSERT", 6);
            sqlKeywords.add("IDENTITYCOL", 6);
            sqlKeywords.add("ID", 6);
            sqlKeywords.add("IF", 6);
            sqlKeywords.add("INDEX", 6);
            sqlKeywords.add("INNER", 6);
            sqlKeywords.add("INSERT", 6);
            sqlKeywords.add("INTO", 6);
            sqlKeywords.add("IS", 6);
            sqlKeywords.add("ISOLATION", 6);
            sqlKeywords.add("KEY", 6);
            sqlKeywords.add("KILL", 6);
            sqlKeywords.add("LEVEL", 6);
            sqlKeywords.add("LINENO", 6);
            sqlKeywords.add("LOAD", 6);
            sqlKeywords.add("MAX", 6);
            sqlKeywords.add("MIN", 6);
            sqlKeywords.add("MIRROREXIT", 6);
            sqlKeywords.add("NATIONAL", 6);
            sqlKeywords.add("NOCHECK", 6);
            sqlKeywords.add("NONCLUSTERED", 6);
            sqlKeywords.add("OF", 6);
            sqlKeywords.add("OFF", 6);
            sqlKeywords.add("OFFSETS", 6);
            sqlKeywords.add("ON", 6);
            sqlKeywords.add("ONCE", 6);
            sqlKeywords.add("ONLY", 6);
            sqlKeywords.add("OPEN", 6);
            sqlKeywords.add("OPENDATASOURCE", 6);
            sqlKeywords.add("OPENQUERY", 6);
            sqlKeywords.add("OPENROWSET", 6);
            sqlKeywords.add("OPTION", 6);
            sqlKeywords.add("ORDER", 6);
            sqlKeywords.add("OVER", 6);
            sqlKeywords.add("PERCENT", 6);
            sqlKeywords.add("PERM", 6);
            sqlKeywords.add("PERMANENT", 6);
            sqlKeywords.add("PIPE", 6);
            sqlKeywords.add("PLAN", 6);
            sqlKeywords.add("PRECISION", 6);
            sqlKeywords.add("PREPARE", 6);
            sqlKeywords.add("PRIMARY", 6);
            sqlKeywords.add("PRINT", 6);
            sqlKeywords.add("PRIVILEGES", 6);
            sqlKeywords.add("PROC", 6);
            sqlKeywords.add("PROCEDURE", 6);
            sqlKeywords.add("PROCESSEXIT", 6);
            sqlKeywords.add("PUBLIC", 6);
            sqlKeywords.add("QUOTED_IDENTIFIER", 6);
            sqlKeywords.add("RAISERROR", 6);
            sqlKeywords.add("READ", 6);
            sqlKeywords.add("READTEXT", 6);
            sqlKeywords.add("RECONFIGURE", 6);
            sqlKeywords.add("REFERENCES", 6);
            sqlKeywords.add("REPEATABLE", 6);
            sqlKeywords.add("REPLICATION", 6);
            sqlKeywords.add("RESTORE", 6);
            sqlKeywords.add("RESTRICT", 6);
            sqlKeywords.add("RETURN", 6);
            sqlKeywords.add("REVOKE", 6);
            sqlKeywords.add("ROLLBACK", 6);
            sqlKeywords.add("ROWGUIDCOL", 6);
            sqlKeywords.add("RULE", 6);
            sqlKeywords.add("SAVE", 6);
            sqlKeywords.add("SCHEMA", 6);
            sqlKeywords.add("SELECT", 6);
            sqlKeywords.add("SERIALIZABLE", 6);
            sqlKeywords.add("SET", 6);
            sqlKeywords.add("SETUSER", 6);
            sqlKeywords.add("SHUTDOWN", 6);
            sqlKeywords.add("STATISTICS", 6);
            sqlKeywords.add("TABLE", 6);
            sqlKeywords.add("TAPE", 6);
            sqlKeywords.add("TEMP", 6);
            sqlKeywords.add("TEMPORARY", 6);
            sqlKeywords.add("TEXTIMAGE_ON", 6);
            sqlKeywords.add("THEN", 6);
            sqlKeywords.add("TO", 6);
            sqlKeywords.add("TOP", 6);
            sqlKeywords.add("TRAN", 6);
            sqlKeywords.add("TRANSACTION", 6);
            sqlKeywords.add("TRIGGER", 6);
            sqlKeywords.add("TRUNCATE", 6);
            sqlKeywords.add("TSEQUAL", 6);
            sqlKeywords.add("UNCOMMITTED", 6);
            sqlKeywords.add("UNION", 6);
            sqlKeywords.add("UNIQUE", 6);
            sqlKeywords.add("UPDATE", 6);
            sqlKeywords.add("UPDATETEXT", 6);
            sqlKeywords.add("USE", 6);
            sqlKeywords.add("VALUES", 6);
            sqlKeywords.add("VARYING", 6);
            sqlKeywords.add("VIEW", 6);
            sqlKeywords.add("WAITFOR", 6);
            sqlKeywords.add("WHEN", 6);
            sqlKeywords.add("WHERE", 6);
            sqlKeywords.add("WHILE", 6);
            sqlKeywords.add("WITH", 6);
            sqlKeywords.add("WORK", 6);
            sqlKeywords.add("WRITETEXT", 6);
            sqlKeywords.add("binary", 6);
            sqlKeywords.add("bit", 6);
            sqlKeywords.add("char", 6);
            sqlKeywords.add("character", 6);
            sqlKeywords.add("datetime", 6);
            sqlKeywords.add("decimal", 6);
            sqlKeywords.add("float", 6);
            sqlKeywords.add("image", 6);
            sqlKeywords.add("int", 6);
            sqlKeywords.add("integer", 6);
            sqlKeywords.add("money", 6);
            sqlKeywords.add("name", 6);
            sqlKeywords.add("numeric", 6);
            sqlKeywords.add("nchar", 6);
            sqlKeywords.add("nvarchar", 6);
            sqlKeywords.add("ntext", 6);
            sqlKeywords.add("real", 6);
            sqlKeywords.add("smalldatetime", 6);
            sqlKeywords.add("smallint", 6);
            sqlKeywords.add("smallmoney", 6);
            sqlKeywords.add("text", 6);
            sqlKeywords.add("timestamp", 6);
            sqlKeywords.add("tinyint", 6);
            sqlKeywords.add("uniqueidentifier", 6);
            sqlKeywords.add("varbinary", 6);
            sqlKeywords.add("varchar", 6);
            sqlKeywords.add("@@CONNECTIONS", 7);
            sqlKeywords.add("@@CPU_BUSY", 7);
            sqlKeywords.add("@@CURSOR_ROWS", 7);
            sqlKeywords.add("@@DATEFIRST", 7);
            sqlKeywords.add("@@DBTS", 7);
            sqlKeywords.add("@@ERROR", 7);
            sqlKeywords.add("@@FETCH_STATUS", 7);
            sqlKeywords.add("@@IDENTITY", 7);
            sqlKeywords.add("@@IDLE", 7);
            sqlKeywords.add("@@IO_BUSY", 7);
            sqlKeywords.add("@@LANGID", 7);
            sqlKeywords.add("@@LANGUAGE", 7);
            sqlKeywords.add("@@LOCK_TIMEOUT", 7);
            sqlKeywords.add("@@MAX_CONNECTIONS", 7);
            sqlKeywords.add("@@MAX_PRECISION", 7);
            sqlKeywords.add("@@NESTLEVEL", 7);
            sqlKeywords.add("@@OPTIONS", 7);
            sqlKeywords.add("@@PACK_RECEIVED", 7);
            sqlKeywords.add("@@PACK_SENT", 7);
            sqlKeywords.add("@@PACKET_ERRORS", 7);
            sqlKeywords.add("@@PROCID", 7);
            sqlKeywords.add("@@REMSERVER", 7);
            sqlKeywords.add("@@ROWCOUNT", 7);
            sqlKeywords.add("@@SERVERNAME", 7);
            sqlKeywords.add("@@SERVICENAME", 7);
            sqlKeywords.add("@@SPID", 7);
            sqlKeywords.add("@@TEXTSIZE", 7);
            sqlKeywords.add("@@TIMETICKS", 7);
            sqlKeywords.add("@@TOTAL_ERRORS", 7);
            sqlKeywords.add("@@TOTAL_READ", 7);
            sqlKeywords.add("@@TOTAL_WRITE", 7);
            sqlKeywords.add("@@TRANCOUNT", 7);
            sqlKeywords.add("@@VERSION", 7);
            sqlKeywords.add("ABS", 7);
            sqlKeywords.add("ACOS", 7);
            sqlKeywords.add("APP_NAME", 7);
            sqlKeywords.add("ASCII", 7);
            sqlKeywords.add("ASIN", 7);
            sqlKeywords.add("ATAN", 7);
            sqlKeywords.add("ATN2", 7);
            sqlKeywords.add("AVG", 7);
            sqlKeywords.add("CASE", 7);
            sqlKeywords.add("CAST", 7);
            sqlKeywords.add("CEILING", 7);
            sqlKeywords.add("CHARINDEX", 7);
            sqlKeywords.add("COALESCE", 7);
            sqlKeywords.add("COL_LENGTH", 7);
            sqlKeywords.add("COL_NAME", 7);
            sqlKeywords.add("COLUMNPROPERTY", 7);
            sqlKeywords.add("CONVERT", 7);
            sqlKeywords.add("COS", 7);
            sqlKeywords.add("COT", 7);
            sqlKeywords.add("COUNT", 7);
            sqlKeywords.add("CURRENT_TIME", 7);
            sqlKeywords.add("CURRENT_DATE", 7);
            sqlKeywords.add("CURRENT_TIMESTAMP", 7);
            sqlKeywords.add("CURRENT_USER", 7);
            sqlKeywords.add("CURSOR_STATUS", 7);
            sqlKeywords.add("DATABASEPROPERTY", 7);
            sqlKeywords.add("DATALENGTH", 7);
            sqlKeywords.add("DATEADD", 7);
            sqlKeywords.add("DATEDIFF", 7);
            sqlKeywords.add("DATENAME", 7);
            sqlKeywords.add("DATEPART", 7);
            sqlKeywords.add("DAY", 7);
            sqlKeywords.add("DB_ID", 7);
            sqlKeywords.add("DB_NAME", 7);
            sqlKeywords.add("DEGREES", 7);
            sqlKeywords.add("DIFFERENCE", 7);
            sqlKeywords.add("EXP", 7);
            sqlKeywords.add("FILE_ID", 7);
            sqlKeywords.add("FILE_NAME", 7);
            sqlKeywords.add("FILEGROUP_ID", 7);
            sqlKeywords.add("FILEGROUP_NAME", 7);
            sqlKeywords.add("FILEGROUPPROPERTY", 7);
            sqlKeywords.add("FILEPROPERTY", 7);
            sqlKeywords.add("FLOOR", 7);
            sqlKeywords.add("FORMATMESSAGE", 7);
            sqlKeywords.add("FULLTEXTCATALOGPROPERTY", 7);
            sqlKeywords.add("FULLTEXTSERVICEPROPERTY", 7);
            sqlKeywords.add("GETANSINULL", 7);
            sqlKeywords.add("GETDATE", 7);
            sqlKeywords.add("HOST_ID", 7);
            sqlKeywords.add("HOST_NAME", 7);
            sqlKeywords.add("IDENT_INCR", 7);
            sqlKeywords.add("IDENT_SEED", 7);
            sqlKeywords.add("IDENTITY_INSERT", 7);
            sqlKeywords.add("INDEX_COL", 7);
            sqlKeywords.add("INDEXPROPERTY", 7);
            sqlKeywords.add("IS_MEMBER", 7);
            sqlKeywords.add("IS_SRVROLEMEMBER", 7);
            sqlKeywords.add("ISDATE", 7);
            sqlKeywords.add("ISNULL", 7);
            sqlKeywords.add("ISNUMERIC", 7);
            sqlKeywords.add("LEFT", 7);
            sqlKeywords.add("LEN", 7);
            sqlKeywords.add("LOG", 7);
            sqlKeywords.add("LOG10", 7);
            sqlKeywords.add("LOWER", 7);
            sqlKeywords.add("LTRIM", 7);
            sqlKeywords.add("MONTH", 7);
            sqlKeywords.add("NEWID", 7);
            sqlKeywords.add("NULLIF", 7);
            sqlKeywords.add("OBJECT_ID", 7);
            sqlKeywords.add("OBJECT_NAME", 7);
            sqlKeywords.add("OBJECTPROPERTY", 7);
            sqlKeywords.add("PARSENAME", 7);
            sqlKeywords.add("PATINDEX", 7);
            sqlKeywords.add("PERMISSIONS", 7);
            sqlKeywords.add("PI", 7);
            sqlKeywords.add("POWER", 7);
            sqlKeywords.add("QUOTENAME", 7);
            sqlKeywords.add("RADIANS", 7);
            sqlKeywords.add("RAND", 7);
            sqlKeywords.add("REPLACE", 7);
            sqlKeywords.add("REPLICATE", 7);
            sqlKeywords.add("REVERSE", 7);
            sqlKeywords.add("RIGHT", 7);
            sqlKeywords.add("ROUND", 7);
            sqlKeywords.add("RTRIM", 7);
            sqlKeywords.add("SESSION_USER", 7);
            sqlKeywords.add("SIGN", 7);
            sqlKeywords.add("SIN", 7);
            sqlKeywords.add("SOUNDEX", 7);
            sqlKeywords.add("SPACE", 7);
            sqlKeywords.add("SQRT", 7);
            sqlKeywords.add("SQUARE", 7);
            sqlKeywords.add("STATS_DATE", 7);
            sqlKeywords.add("STR", 7);
            sqlKeywords.add("STUFF", 7);
            sqlKeywords.add("SUBSTRING", 7);
            sqlKeywords.add("SUSER_ID", 7);
            sqlKeywords.add("SUSER_NAME", 7);
            sqlKeywords.add("SUSER_SID", 7);
            sqlKeywords.add("SUSER_SNAME", 7);
            sqlKeywords.add("SYSTEM_USER", 7);
            sqlKeywords.add("TAN", 7);
            sqlKeywords.add("TEXTPTR", 7);
            sqlKeywords.add("TEXTVALID", 7);
            sqlKeywords.add("TYPEPROPERTY", 7);
            sqlKeywords.add("UNICODE", 7);
            sqlKeywords.add("UPPER", 7);
            sqlKeywords.add("USER_ID", 7);
            sqlKeywords.add("USER_NAME", 7);
            sqlKeywords.add("USER", 7);
            sqlKeywords.add("YEAR", 7);
            sqlKeywords.add("ALL", 6);
            sqlKeywords.add("AND", 6);
            sqlKeywords.add("ANY", 6);
            sqlKeywords.add("BETWEEN", 6);
            sqlKeywords.add("CROSS", 6);
            sqlKeywords.add("EXISTS", 6);
            sqlKeywords.add("IN", 6);
            sqlKeywords.add("INTERSECT", 6);
            sqlKeywords.add("JOIN", 6);
            sqlKeywords.add("LIKE", 6);
            sqlKeywords.add("NOT", 6);
            sqlKeywords.add("NULL", 6);
            sqlKeywords.add("OR", 6);
            sqlKeywords.add("OUTER", 6);
            sqlKeywords.add("SOME", 6);
            sqlKeywords.add("sp_add_agent_parameter", 8);
            sqlKeywords.add("sp_add_agent_profile", 8);
            sqlKeywords.add("sp_add_alert", 8);
            sqlKeywords.add("sp_add_category", 8);
            sqlKeywords.add("sp_add_data_file_recover_suspect_db", 8);
            sqlKeywords.add("sp_add_job", 8);
            sqlKeywords.add("sp_add_jobschedule", 8);
            sqlKeywords.add("sp_add_jobserver", 8);
            sqlKeywords.add("sp_add_jobstep", 8);
            sqlKeywords.add("sp_add_log_file_recover_suspect_db", 8);
            sqlKeywords.add("sp_add_notification", 8);
            sqlKeywords.add("sp_add_operator", 8);
            sqlKeywords.add("sp_add_targetservergroup", 8);
            sqlKeywords.add("sp_add_targetsvrgrp_member", 8);
            sqlKeywords.add("sp_addalias", 8);
            sqlKeywords.add("sp_addapprole", 8);
            sqlKeywords.add("sp_addarticle", 8);
            sqlKeywords.add("sp_adddistpublisher", 8);
            sqlKeywords.add("sp_adddistributiondb", 8);
            sqlKeywords.add("sp_adddistributor", 8);
            sqlKeywords.add("sp_addextendedproc", 8);
            sqlKeywords.add("sp_addgroup", 8);
            sqlKeywords.add("sp_addlinkedserver", 8);
            sqlKeywords.add("sp_addlinkedsrvlogin", 8);
            sqlKeywords.add("sp_addlinkedsrvlogin", 8);
            sqlKeywords.add("sp_addlogin", 8);
            sqlKeywords.add("sp_addmergearticle", 8);
            sqlKeywords.add("sp_addmergefilter", 8);
            sqlKeywords.add("sp_addmergepublication", 8);
            sqlKeywords.add("sp_addmergepullsubscription", 8);
            sqlKeywords.add("sp_addmergepullsubscription_agent", 8);
            sqlKeywords.add("sp_addmergesubscription", 8);
            sqlKeywords.add("sp_addmessage", 8);
            sqlKeywords.add("sp_addpublication", 8);
            sqlKeywords.add("sp_addpublication_snapshot", 8);
            sqlKeywords.add("sp_addpublisher70", 8);
            sqlKeywords.add("sp_addpullsubscription", 8);
            sqlKeywords.add("sp_addpullsubscription_agent", 8);
            sqlKeywords.add("sp_addremotelogin", 8);
            sqlKeywords.add("sp_addrole", 8);
            sqlKeywords.add("sp_addrolemember", 8);
            sqlKeywords.add("sp_addserver", 8);
            sqlKeywords.add("sp_addsrvrolemember", 8);
            sqlKeywords.add("sp_addsubscriber", 8);
            sqlKeywords.add("sp_addsubscriber_schedule", 8);
            sqlKeywords.add("sp_addsubscription", 8);
            sqlKeywords.add("sp_addsynctriggers", 8);
            sqlKeywords.add("sp_addtabletocontents", 8);
            sqlKeywords.add("sp_addtask", 8);
            sqlKeywords.add("sp_addtype", 8);
            sqlKeywords.add("sp_addumpdevice", 8);
            sqlKeywords.add("sp_adduser", 8);
            sqlKeywords.add("sp_altermessage", 8);
            sqlKeywords.add("sp_apply_job_to_targets", 8);
            sqlKeywords.add("sp_approlepassword", 8);
            sqlKeywords.add("sp_article_validation", 8);
            sqlKeywords.add("sp_articlecolumn", 8);
            sqlKeywords.add("sp_articlefilter", 8);
            sqlKeywords.add("sp_articlesynctranprocs", 8);
            sqlKeywords.add("sp_articleview", 8);
            sqlKeywords.add("sp_attach_db", 8);
            sqlKeywords.add("sp_attach_single_file_db", 8);
            sqlKeywords.add("sp_autostats", 8);
            sqlKeywords.add("sp_bindefault", 8);
            sqlKeywords.add("sp_bindrule", 8);
            sqlKeywords.add("sp_bindsession", 8);
            sqlKeywords.add("sp_browsereplcmds", 8);
            sqlKeywords.add("sp_catalogs", 8);
            sqlKeywords.add("sp_certify_removable", 8);
            sqlKeywords.add("sp_change_agent_parameter", 8);
            sqlKeywords.add("sp_change_agent_profile", 8);
            sqlKeywords.add("sp_change_subscription_properties", 8);
            sqlKeywords.add("sp_change_users_login", 8);
            sqlKeywords.add("sp_changearticle", 8);
            sqlKeywords.add("sp_changedbowner", 8);
            sqlKeywords.add("sp_changedistpublisher", 8);
            sqlKeywords.add("sp_changedistributiondb", 8);
            sqlKeywords.add("sp_changedistributor_password", 8);
            sqlKeywords.add("sp_changedistributor_property", 8);
            sqlKeywords.add("sp_changegroup", 8);
            sqlKeywords.add("sp_changemergearticle", 8);
            sqlKeywords.add("sp_changemergefilter", 8);
            sqlKeywords.add("sp_changemergepublication", 8);
            sqlKeywords.add("sp_changemergepullsubscription", 8);
            sqlKeywords.add("sp_changemergesubscription", 8);
            sqlKeywords.add("sp_changeobjectowner", 8);
            sqlKeywords.add("sp_changepublication", 8);
            sqlKeywords.add("sp_changesubscriber", 8);
            sqlKeywords.add("sp_changesubscriber_schedule", 8);
            sqlKeywords.add("sp_changesubstatus", 8);
            sqlKeywords.add("sp_check_for_sync_trigger", 8);
            sqlKeywords.add("sp_column_privileges", 8);
            sqlKeywords.add("sp_column_privileges_ex", 8);
            sqlKeywords.add("sp_columns", 8);
            sqlKeywords.add("sp_columns_ex", 8);
            sqlKeywords.add("sp_configure", 8);
            sqlKeywords.add("sp_create_removable", 8);
            sqlKeywords.add("sp_createorphan", 8);
            sqlKeywords.add("sp_createstats", 8);
            sqlKeywords.add("sp_cursor", 8);
            sqlKeywords.add("sp_cursor_list", 8);
            sqlKeywords.add("sp_cursorclose", 8);
            sqlKeywords.add("sp_cursorexecute", 8);
            sqlKeywords.add("sp_cursorfetch", 8);
            sqlKeywords.add("sp_cursoropen", 8);
            sqlKeywords.add("sp_cursoroption", 8);
            sqlKeywords.add("sp_cursorprepare", 8);
            sqlKeywords.add("sp_cursorunprepare", 8);
            sqlKeywords.add("sp_cycle_errorlog", 8);
            sqlKeywords.add("sp_databases", 8);
            sqlKeywords.add("sp_datatype_info", 8);
            sqlKeywords.add("sp_dbcmptlevel", 8);
            sqlKeywords.add("sp_dbfixedrolepermission", 8);
            sqlKeywords.add("sp_dboption", 8);
            sqlKeywords.add("sp_defaultdb", 8);
            sqlKeywords.add("sp_defaultlanguage", 8);
            sqlKeywords.add("sp_delete_alert", 8);
            sqlKeywords.add("sp_delete_backuphistory", 8);
            sqlKeywords.add("sp_delete_category", 8);
            sqlKeywords.add("sp_delete_job", 8);
            sqlKeywords.add("sp_delete_jobschedule", 8);
            sqlKeywords.add("sp_delete_jobserver", 8);
            sqlKeywords.add("sp_delete_jobstep", 8);
            sqlKeywords.add("sp_delete_notification", 8);
            sqlKeywords.add("sp_delete_operator", 8);
            sqlKeywords.add("sp_delete_targetserver", 8);
            sqlKeywords.add("sp_delete_targetservergroup", 8);
            sqlKeywords.add("sp_delete_targetsvrgrp_member", 8);
            sqlKeywords.add("sp_deletemergeconflictrow", 8);
            sqlKeywords.add("sp_denylogin", 8);
            sqlKeywords.add("sp_depends", 8);
            sqlKeywords.add("sp_describe_cursor", 8);
            sqlKeywords.add("sp_describe_cursor_columns", 8);
            sqlKeywords.add("sp_describe_cursor_tables", 8);
            sqlKeywords.add("sp_detach_db", 8);
            sqlKeywords.add("sp_drop_agent_parameter", 8);
            sqlKeywords.add("sp_drop_agent_profile", 8);
            sqlKeywords.add("sp_dropalias", 8);
            sqlKeywords.add("sp_dropapprole", 8);
            sqlKeywords.add("sp_droparticle", 8);
            sqlKeywords.add("sp_dropdevice", 8);
            sqlKeywords.add("sp_dropdistpublisher", 8);
            sqlKeywords.add("sp_dropdistributiondb", 8);
            sqlKeywords.add("sp_dropdistributor", 8);
            sqlKeywords.add("sp_dropextendedproc", 8);
            sqlKeywords.add("sp_dropgroup", 8);
            sqlKeywords.add("sp_droplinkedsrvlogin", 8);
            sqlKeywords.add("sp_droplinkedsrvlogin", 8);
            sqlKeywords.add("sp_droplogin", 8);
            sqlKeywords.add("sp_dropmergearticle", 8);
            sqlKeywords.add("sp_dropmergefilter", 8);
            sqlKeywords.add("sp_dropmergepublication", 8);
            sqlKeywords.add("sp_dropmergepullsubscription", 8);
            sqlKeywords.add("sp_dropmergesubscription", 8);
            sqlKeywords.add("sp_dropmessage", 8);
            sqlKeywords.add("sp_droporphans", 8);
            sqlKeywords.add("sp_droppublication", 8);
            sqlKeywords.add("sp_droppullsubscription", 8);
            sqlKeywords.add("sp_dropremotelogin", 8);
            sqlKeywords.add("sp_droprole", 8);
            sqlKeywords.add("sp_droprolemember", 8);
            sqlKeywords.add("sp_dropserver", 8);
            sqlKeywords.add("sp_dropsrvrolemember", 8);
            sqlKeywords.add("sp_dropsubscriber", 8);
            sqlKeywords.add("sp_dropsubscription", 8);
            sqlKeywords.add("sp_droptask", 8);
            sqlKeywords.add("sp_droptype", 8);
            sqlKeywords.add("sp_dropuser", 8);
            sqlKeywords.add("sp_dropwebtask", 8);
            sqlKeywords.add("sp_dsninfo", 8);
            sqlKeywords.add("sp_dumpparamcmd", 8);
            sqlKeywords.add("sp_enumcodepages", 8);
            sqlKeywords.add("sp_enumcustomresolvers", 8);
            sqlKeywords.add("sp_enumdsn", 8);
            sqlKeywords.add("sp_enumfullsubscribers", 8);
            sqlKeywords.add("sp_execute", 8);
            sqlKeywords.add("sp_executesql", 8);
            sqlKeywords.add("sp_expired_subscription_cleanup", 8);
            sqlKeywords.add("sp_fkeys", 8);
            sqlKeywords.add("sp_foreignkeys", 8);
            sqlKeywords.add("sp_fulltext_catalog", 8);
            sqlKeywords.add("sp_fulltext_column", 8);
            sqlKeywords.add("sp_fulltext_database", 8);
            sqlKeywords.add("sp_fulltext_service", 8);
            sqlKeywords.add("sp_fulltext_table", 8);
            sqlKeywords.add("sp_generatefilters", 8);
            sqlKeywords.add("sp_get_distributor", 8);
            sqlKeywords.add("sp_getbindtoken", 8);
            sqlKeywords.add("sp_getmergedeletetype", 8);
            sqlKeywords.add("sp_grant_publication_access", 8);
            sqlKeywords.add("sp_grantdbaccess", 8);
            sqlKeywords.add("sp_grantlogin", 8);
            sqlKeywords.add("sp_help", 8);
            sqlKeywords.add("sp_help_agent_default", 8);
            sqlKeywords.add("sp_help_agent_parameter", 8);
            sqlKeywords.add("sp_help_agent_profile", 8);
            sqlKeywords.add("sp_help_alert", 8);
            sqlKeywords.add("sp_help_category", 8);
            sqlKeywords.add("sp_help_downloadlist", 8);
            sqlKeywords.add("sp_help_fulltext_catalogs", 8);
            sqlKeywords.add("sp_help_fulltext_catalogs_cursor", 8);
            sqlKeywords.add("sp_help_fulltext_columns", 8);
            sqlKeywords.add("sp_help_fulltext_columns_cursor", 8);
            sqlKeywords.add("sp_help_fulltext_tables", 8);
            sqlKeywords.add("sp_help_fulltext_tables_cursor", 8);
            sqlKeywords.add("sp_help_job", 8);
            sqlKeywords.add("sp_help_jobhistory", 8);
            sqlKeywords.add("sp_help_jobschedule", 8);
            sqlKeywords.add("sp_help_jobserver", 8);
            sqlKeywords.add("sp_help_jobstep", 8);
            sqlKeywords.add("sp_help_notification", 8);
            sqlKeywords.add("sp_help_operator", 8);
            sqlKeywords.add("sp_help_publication_access", 8);
            sqlKeywords.add("sp_help_targetserver", 8);
            sqlKeywords.add("sp_help_targetservergroup", 8);
            sqlKeywords.add("sp_helparticle", 8);
            sqlKeywords.add("sp_helparticlecolumns", 8);
            sqlKeywords.add("sp_helpconstraint", 8);
            sqlKeywords.add("sp_helpdb", 8);
            sqlKeywords.add("sp_helpdbfixedrole", 8);
            sqlKeywords.add("sp_helpdevice", 8);
            sqlKeywords.add("sp_helpdistpublisher", 8);
            sqlKeywords.add("sp_helpdistributiondb", 8);
            sqlKeywords.add("sp_helpdistributor", 8);
            sqlKeywords.add("sp_helpextendedproc", 8);
            sqlKeywords.add("sp_helpfile", 8);
            sqlKeywords.add("sp_helpfilegroup", 8);
            sqlKeywords.add("sp_helpgroup", 8);
            sqlKeywords.add("sp_helphistory", 8);
            sqlKeywords.add("sp_helpindex", 8);
            sqlKeywords.add("sp_helplanguage", 8);
            sqlKeywords.add("sp_helplinkedsrvlogin", 8);
            sqlKeywords.add("sp_helplogins", 8);
            sqlKeywords.add("sp_helpmergearticle", 8);
            sqlKeywords.add("sp_helpmergearticleconflicts", 8);
            sqlKeywords.add("sp_helpmergeconflictrows", 8);
            sqlKeywords.add("sp_helpmergedeleteconflictrows", 8);
            sqlKeywords.add("sp_helpmergefilter", 8);
            sqlKeywords.add("sp_helpmergepublication", 8);
            sqlKeywords.add("sp_helpmergepullsubscription", 8);
            sqlKeywords.add("sp_helpmergesubscription", 8);
            sqlKeywords.add("sp_helpntgroup", 8);
            sqlKeywords.add("sp_helppublication", 8);
            sqlKeywords.add("sp_helppullsubscription", 8);
            sqlKeywords.add("sp_helpremotelogin", 8);
            sqlKeywords.add("sp_helpreplicationdboption", 8);
            sqlKeywords.add("sp_helprole", 8);
            sqlKeywords.add("sp_helprolemember", 8);
            sqlKeywords.add("sp_helprotect", 8);
            sqlKeywords.add("sp_helpserver", 8);
            sqlKeywords.add("sp_helpsort", 8);
            sqlKeywords.add("sp_helpsrvrole", 8);
            sqlKeywords.add("sp_helpsrvrolemember", 8);
            sqlKeywords.add("sp_helpsubscriberinfo", 8);
            sqlKeywords.add("sp_helpsubscription", 8);
            sqlKeywords.add("sp_helpsubscription_properties", 8);
            sqlKeywords.add("sp_helptask", 8);
            sqlKeywords.add("sp_helptext", 8);
            sqlKeywords.add("sp_helptrigger", 8);
            sqlKeywords.add("sp_helpuser", 8);
            sqlKeywords.add("sp_indexes", 8);
            sqlKeywords.add("sp_indexoption", 8);
            sqlKeywords.add("sp_link_publication", 8);
            sqlKeywords.add("sp_linkedservers", 8);
            sqlKeywords.add("sp_lock", 8);
            sqlKeywords.add("sp_makewebtask", 8);
            sqlKeywords.add("sp_manage_jobs_by_login", 8);
            sqlKeywords.add("sp_mergedummyupdate", 8);
            sqlKeywords.add("sp_mergesubscription_cleanup", 8);
            sqlKeywords.add("sp_monitor", 8);
            sqlKeywords.add("sp_msx_defect", 8);
            sqlKeywords.add("sp_msx_enlist", 8);
            sqlKeywords.add("sp_OACreate", 8);
            sqlKeywords.add("sp_OADestroy", 8);
            sqlKeywords.add("sp_OAGetErrorInfo", 8);
            sqlKeywords.add("sp_OAGetProperty", 8);
            sqlKeywords.add("sp_OAMethod", 8);
            sqlKeywords.add("sp_OASetProperty", 8);
            sqlKeywords.add("sp_OAStop", 8);
            sqlKeywords.add("sp_password", 8);
            sqlKeywords.add("sp_pkeys", 8);
            sqlKeywords.add("sp_post_msx_operation", 8);
            sqlKeywords.add("sp_prepare", 8);
            sqlKeywords.add("sp_primarykeys", 8);
            sqlKeywords.add("sp_processmail", 8);
            sqlKeywords.add("sp_procoption", 8);
            sqlKeywords.add("sp_publication_validation", 8);
            sqlKeywords.add("sp_purge_jobhistory", 8);
            sqlKeywords.add("sp_purgehistory", 8);
            sqlKeywords.add("sp_reassigntask", 8);
            sqlKeywords.add("sp_recompile", 8);
            sqlKeywords.add("sp_refreshsubscriptions", 8);
            sqlKeywords.add("sp_refreshview", 8);
            sqlKeywords.add("sp_reinitmergepullsubscription", 8);
            sqlKeywords.add("sp_reinitmergesubscription", 8);
            sqlKeywords.add("sp_reinitpullsubscription", 8);
            sqlKeywords.add("sp_reinitsubscription", 8);
            sqlKeywords.add("sp_remoteoption", 8);
            sqlKeywords.add("sp_remove_job_from_targets", 8);
            sqlKeywords.add("sp_removedbreplication", 8);
            sqlKeywords.add("sp_rename", 8);
            sqlKeywords.add("sp_renamedb", 8);
            sqlKeywords.add("sp_replcmds", 8);
            sqlKeywords.add("sp_replcounters", 8);
            sqlKeywords.add("sp_repldone", 8);
            sqlKeywords.add("sp_replflush", 8);
            sqlKeywords.add("sp_replication_agent_checkup", 8);
            sqlKeywords.add("sp_replicationdboption", 8);
            sqlKeywords.add("sp_replsetoriginator", 8);
            sqlKeywords.add("sp_replshowcmds", 8);
            sqlKeywords.add("sp_repltrans", 8);
            sqlKeywords.add("sp_reset_connection", 8);
            sqlKeywords.add("sp_resync_targetserver", 8);
            sqlKeywords.add("sp_revoke_publication_access", 8);
            sqlKeywords.add("sp_revokedbaccess", 8);
            sqlKeywords.add("sp_revokelogin", 8);
            sqlKeywords.add("sp_runwebtask", 8);
            sqlKeywords.add("sp_script_synctran_commands", 8);
            sqlKeywords.add("sp_scriptdelproc", 8);
            sqlKeywords.add("sp_scriptinsproc", 8);
            sqlKeywords.add("sp_scriptmappedupdproc", 8);
            sqlKeywords.add("sp_scriptupdproc", 8);
            sqlKeywords.add("sp_sdidebug", 8);
            sqlKeywords.add("sp_server_info", 8);
            sqlKeywords.add("sp_serveroption", 8);
            sqlKeywords.add("sp_serveroption", 8);
            sqlKeywords.add("sp_setapprole", 8);
            sqlKeywords.add("sp_setnetname", 8);
            sqlKeywords.add("sp_spaceused", 8);
            sqlKeywords.add("sp_special_columns", 8);
            sqlKeywords.add("sp_sproc_columns", 8);
            sqlKeywords.add("sp_srvrolepermission", 8);
            sqlKeywords.add("sp_start_job", 8);
            sqlKeywords.add("sp_statistics", 8);
            sqlKeywords.add("sp_stop_job", 8);
            sqlKeywords.add("sp_stored_procedures", 8);
            sqlKeywords.add("sp_subscription_cleanup", 8);
            sqlKeywords.add("sp_table_privileges", 8);
            sqlKeywords.add("sp_table_privileges_ex", 8);
            sqlKeywords.add("sp_table_validation", 8);
            sqlKeywords.add("sp_tableoption", 8);
            sqlKeywords.add("sp_tables", 8);
            sqlKeywords.add("sp_tables_ex", 8);
            sqlKeywords.add("sp_unbindefault", 8);
            sqlKeywords.add("sp_unbindrule", 8);
            sqlKeywords.add("sp_unprepare", 8);
            sqlKeywords.add("sp_update_agent_profile", 8);
            sqlKeywords.add("sp_update_alert", 8);
            sqlKeywords.add("sp_update_category", 8);
            sqlKeywords.add("sp_update_job", 8);
            sqlKeywords.add("sp_update_jobschedule", 8);
            sqlKeywords.add("sp_update_jobstep", 8);
            sqlKeywords.add("sp_update_notification", 8);
            sqlKeywords.add("sp_update_operator", 8);
            sqlKeywords.add("sp_update_targetservergroup", 8);
            sqlKeywords.add("sp_updatestats", 8);
            sqlKeywords.add("sp_updatetask", 8);
            sqlKeywords.add("sp_validatelogins", 8);
            sqlKeywords.add("sp_validname", 8);
            sqlKeywords.add("sp_who", 8);
            sqlKeywords.add("xp_cmdshell", 8);
            sqlKeywords.add("xp_deletemail", 8);
            sqlKeywords.add("xp_enumgroups", 8);
            sqlKeywords.add("xp_findnextmsg", 8);
            sqlKeywords.add("xp_findnextmsg", 8);
            sqlKeywords.add("xp_grantlogin", 8);
            sqlKeywords.add("xp_logevent", 8);
            sqlKeywords.add("xp_loginconfig", 8);
            sqlKeywords.add("xp_logininfo", 8);
            sqlKeywords.add("xp_msver", 8);
            sqlKeywords.add("xp_readmail", 8);
            sqlKeywords.add("xp_revokelogin", 8);
            sqlKeywords.add("xp_sendmail", 8);
            sqlKeywords.add("xp_sprintf", 8);
            sqlKeywords.add("xp_sqlinventory", 8);
            sqlKeywords.add("xp_sqlmaint", 8);
            sqlKeywords.add("xp_sqltrace", 8);
            sqlKeywords.add("xp_sscanf", 8);
            sqlKeywords.add("xp_startmail", 8);
            sqlKeywords.add("xp_stopmail", 8);
            sqlKeywords.add("xp_trace_addnewqueue", 8);
            sqlKeywords.add("xp_trace_deletequeuedefinition", 8);
            sqlKeywords.add("xp_trace_destroyqueue", 8);
            sqlKeywords.add("xp_trace_enumqueuedefname", 8);
            sqlKeywords.add("xp_trace_enumqueuehandles", 8);
            sqlKeywords.add("xp_trace_eventclassrequired", 8);
            sqlKeywords.add("xp_trace_flushqueryhistory", 8);
            sqlKeywords.add("xp_trace_generate_event", 8);
            sqlKeywords.add("xp_trace_getappfilter", 8);
            sqlKeywords.add("xp_trace_getconnectionidfilter", 8);
            sqlKeywords.add("xp_trace_getcpufilter", 8);
            sqlKeywords.add("xp_trace_getdbidfilter", 8);
            sqlKeywords.add("xp_trace_getdurationfilter", 8);
            sqlKeywords.add("xp_trace_geteventfilter", 8);
            sqlKeywords.add("xp_trace_geteventnames", 8);
            sqlKeywords.add("xp_trace_getevents", 8);
            sqlKeywords.add("xp_trace_gethostfilter", 8);
            sqlKeywords.add("xp_trace_gethpidfilter", 8);
            sqlKeywords.add("xp_trace_getindidfilter", 8);
            sqlKeywords.add("xp_trace_getntdmfilter", 8);
            sqlKeywords.add("xp_trace_getntnmfilter", 8);
            sqlKeywords.add("xp_trace_getobjidfilter", 8);
            sqlKeywords.add("xp_trace_getqueueautostart", 8);
            sqlKeywords.add("xp_trace_getqueuedestination", 8);
            sqlKeywords.add("xp_trace_getqueueproperties", 8);
            sqlKeywords.add("xp_trace_getreadfilter", 8);
            sqlKeywords.add("xp_trace_getserverfilter", 8);
            sqlKeywords.add("xp_trace_getseverityfilter", 8);
            sqlKeywords.add("xp_trace_getspidfilter", 8);
            sqlKeywords.add("xp_trace_getsysobjectsfilter", 8);
            sqlKeywords.add("xp_trace_gettextfilter", 8);
            sqlKeywords.add("xp_trace_getuserfilter", 8);
            sqlKeywords.add("xp_trace_getwritefilter", 8);
            sqlKeywords.add("xp_trace_loadqueuedefinition", 8);
            sqlKeywords.add("xp_trace_pausequeue", 8);
            sqlKeywords.add("xp_trace_restartqueue", 8);
            sqlKeywords.add("xp_trace_savequeuedefinition", 8);
            sqlKeywords.add("xp_trace_setappfilter", 8);
            sqlKeywords.add("xp_trace_setconnectionidfilter", 8);
            sqlKeywords.add("xp_trace_setcpufilter", 8);
            sqlKeywords.add("xp_trace_setdbidfilter", 8);
            sqlKeywords.add("xp_trace_setdurationfilter", 8);
            sqlKeywords.add("xp_trace_seteventclassrequired", 8);
            sqlKeywords.add("xp_trace_seteventfilter", 8);
            sqlKeywords.add("xp_trace_sethostfilter", 8);
            sqlKeywords.add("xp_trace_sethpidfilter", 8);
            sqlKeywords.add("xp_trace_setindidfilter", 8);
            sqlKeywords.add("xp_trace_setntdmfilter", 8);
            sqlKeywords.add("xp_trace_setntnmfilter", 8);
            sqlKeywords.add("xp_trace_setobjidfilter", 8);
            sqlKeywords.add("xp_trace_setqueryhistory", 8);
            sqlKeywords.add("xp_trace_setqueueautostart", 8);
            sqlKeywords.add("xp_trace_setqueuecreateinfo", 8);
            sqlKeywords.add("xp_trace_setqueuedestination", 8);
            sqlKeywords.add("xp_trace_setreadfilter", 8);
            sqlKeywords.add("xp_trace_setserverfilter", 8);
            sqlKeywords.add("xp_trace_setseverityfilter", 8);
            sqlKeywords.add("xp_trace_setspidfilter", 8);
            sqlKeywords.add("xp_trace_setsysobjectsfilter", 8);
            sqlKeywords.add("xp_trace_settextfilter", 8);
            sqlKeywords.add("xp_trace_setuserfilter", 8);
            sqlKeywords.add("xp_trace_setwritefilter", 8);
            sqlKeywords.add("backupfile", 8);
            sqlKeywords.add("backupmediafamily", 8);
            sqlKeywords.add("backupmediaset", 8);
            sqlKeywords.add("backupset", 8);
            sqlKeywords.add("MSagent_parameters", 8);
            sqlKeywords.add("MSagent_profiles", 8);
            sqlKeywords.add("MSarticles", 8);
            sqlKeywords.add("MSdistpublishers", 8);
            sqlKeywords.add("MSdistribution_agents", 8);
            sqlKeywords.add("MSdistribution_history", 8);
            sqlKeywords.add("MSdistributiondbs", 8);
            sqlKeywords.add("MSdistributor", 8);
            sqlKeywords.add("MSlogreader_agents", 8);
            sqlKeywords.add("MSlogreader_history", 8);
            sqlKeywords.add("MSmerge_agents", 8);
            sqlKeywords.add("MSmerge_contents", 8);
            sqlKeywords.add("MSmerge_delete_conflicts", 8);
            sqlKeywords.add("MSmerge_genhistory", 8);
            sqlKeywords.add("MSmerge_history", 8);
            sqlKeywords.add("MSmerge_replinfo", 8);
            sqlKeywords.add("MSmerge_subscriptions", 8);
            sqlKeywords.add("MSmerge_tombstone", 8);
            sqlKeywords.add("MSpublication_access", 8);
            sqlKeywords.add("Mspublications", 8);
            sqlKeywords.add("Mspublisher_databases", 8);
            sqlKeywords.add("MSrepl_commands", 8);
            sqlKeywords.add("MSrepl_errors", 8);
            sqlKeywords.add("Msrepl_originators", 8);
            sqlKeywords.add("MSrepl_transactions", 8);
            sqlKeywords.add("MSrepl_version", 8);
            sqlKeywords.add("MSreplication_objects", 8);
            sqlKeywords.add("MSreplication_subscriptions", 8);
            sqlKeywords.add("MSsnapshot_agents", 8);
            sqlKeywords.add("MSsnapshot_history", 8);
            sqlKeywords.add("MSsubscriber_info", 8);
            sqlKeywords.add("MSsubscriber_schedule", 8);
            sqlKeywords.add("MSsubscription_properties", 8);
            sqlKeywords.add("MSsubscriptions", 8);
            sqlKeywords.add("restorefile", 8);
            sqlKeywords.add("restorefilegroup", 8);
            sqlKeywords.add("restorehistory", 8);
            sqlKeywords.add("sysalerts", 8);
            sqlKeywords.add("sysallocations", 8);
            sqlKeywords.add("sysaltfiles", 8);
            sqlKeywords.add("sysarticles", 8);
            sqlKeywords.add("sysarticleupdates", 8);
            sqlKeywords.add("syscacheobjects", 8);
            sqlKeywords.add("syscategories", 8);
            sqlKeywords.add("syscharsets", 8);
            sqlKeywords.add("syscolumns", 8);
            sqlKeywords.add("syscomments", 8);
            sqlKeywords.add("sysconfigures", 8);
            sqlKeywords.add("sysconstraints", 8);
            sqlKeywords.add("syscurconfigs", 8);
            sqlKeywords.add("sysdatabases", 8);
            sqlKeywords.add("sysdatabases", 8);
            sqlKeywords.add("sysdepends", 8);
            sqlKeywords.add("sysdevices", 8);
            sqlKeywords.add("sysdownloadlist", 8);
            sqlKeywords.add("sysfilegroups", 8);
            sqlKeywords.add("sysfiles", 8);
            sqlKeywords.add("sysforeignkeys", 8);
            sqlKeywords.add("sysfulltextcatalogs", 8);
            sqlKeywords.add("sysindexes", 8);
            sqlKeywords.add("sysindexkeys", 8);
            sqlKeywords.add("sysjobhistory", 8);
            sqlKeywords.add("sysjobs", 8);
            sqlKeywords.add("sysjobschedules", 8);
            sqlKeywords.add("sysjobservers", 8);
            sqlKeywords.add("sysjobsteps", 8);
            sqlKeywords.add("syslanguages", 8);
            sqlKeywords.add("syslockinfo", 8);
            sqlKeywords.add("syslogins", 8);
            sqlKeywords.add("sysmembers", 8);
            sqlKeywords.add("sysmergearticles", 8);
            sqlKeywords.add("sysmergepublications", 8);
            sqlKeywords.add("sysmergeschemachange", 8);
            sqlKeywords.add("sysmergesubscriptions", 8);
            sqlKeywords.add("sysmergesubsetfilters", 8);
            sqlKeywords.add("sysmessages", 8);
            sqlKeywords.add("sysnotifications", 8);
            sqlKeywords.add("sysobjects", 8);
            sqlKeywords.add("sysobjects", 8);
            sqlKeywords.add("sysoledbusers", 8);
            sqlKeywords.add("sysoperators", 8);
            sqlKeywords.add("sysperfinfo", 8);
            sqlKeywords.add("syspermissions", 8);
            sqlKeywords.add("sysprocesses", 8);
            sqlKeywords.add("sysprotects", 8);
            sqlKeywords.add("syspublications", 8);
            sqlKeywords.add("sysreferences", 8);
            sqlKeywords.add("sysremotelogins", 8);
            sqlKeywords.add("sysreplicationalerts", 8);
            sqlKeywords.add("sysservers", 8);
            sqlKeywords.add("sysservers", 8);
            sqlKeywords.add("syssubscriptions", 8);
            sqlKeywords.add("systargetservergroupmembers", 8);
            sqlKeywords.add("systargetservergroups", 8);
            sqlKeywords.add("systargetservers", 8);
            sqlKeywords.add("systaskids", 8);
            sqlKeywords.add("systypes", 8);
            sqlKeywords.add("sysusers", 8);
        }
        return sqlKeywords;
    }

    private boolean doKeyword(Segment segment, int n, char c) {
        int n2 = n + 1;
        int n3 = n - this.lastKeyword;
        byte by = this.keywords.lookup(segment, this.lastKeyword, n3);
        if (by != 0) {
            if (this.lastKeyword != this.lastOffset) {
                this.addToken(this.lastKeyword - this.lastOffset, 0);
            }
            this.addToken(n3, by);
            this.lastOffset = n;
        }
        this.lastKeyword = n2;
        return false;
    }
}

